source "https://rubygems.org"

gem 'colorize'
gem 'terminal-table'
gem 'irbtools'
gem 'sinatra'

# Extra
# gem 'command_line_reporter', '>=3.0'
# https://github.com/wbailey/command_line_reporter/wiki/Headers-and-Footers

# when you run `bundle console` it will check that you have Gemfile.lock
# then require gem names in Gemfile